// Produced by Lucky 13 (Team 13) for module GDEV60033, Staffordshire University.

#pragma once

#include "CoreMinimal.h"
#include "Components/SceneCaptureComponent2D.h"

#include "ACameraCaptureComponent.generated.h"

class UTextureRenderTarget2D;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FPhotoTakenDelegate);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FRenderTargetIndexUpdatedDelegate, const int32, PreviousIndex);

/**
 * Uses scene capture to export screenshots of the viewport to a render texture.
 * Should only be attached to an AAPlayerCharacter.
 */
UCLASS()
class THEARTOFFEAR_API UADigitalCameraComponent : public USceneCaptureComponent2D
{
	GENERATED_BODY()

	// OVERRIDES
protected:
	UADigitalCameraComponent();
	virtual void BeginPlay() override;

	// INTERFACE
public:
	/** Captures the scene view and applies the viewport to the specified render texture. Broadcasts OnCameraCaptures. */
	UFUNCTION(BlueprintCallable, Category="ADigitalCameraComponent|Interface")
	void TakePhoto();
	
	/** Broadcast when the camera captures the scene. */
	UPROPERTY(BlueprintAssignable, Category="ADigitalCameraComponent|Interface")
	FPhotoTakenDelegate PhotoTakenDelegate;

	/** Broadcast when the camera captures the scene. */
	FRenderTargetIndexUpdatedDelegate RenderTargetIndexUpdatedDelegate;

protected:
	/** Increments RenderTargetIndex. Index loops after last entry to RenderTargets. Broadcasts OnRenderTargetIndexUpdated. */
	void UpdateRenderTargetIndex();

	/** Callback for OnRenderTargetIndexUpdated. */
	UFUNCTION()
	void OnRenderTargetIndexUpdated(const int32 PreviousIndex);

	// PARAMS
protected:
	/** Render targets used to store the photographs generated by this component's scene captures. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category="ADigitalCameraComponent|Params")
	TArray<TSoftObjectPtr<UTextureRenderTarget2D>> RenderTargets;

	/// TODO: Remove the following variable. Just take the last render texture that was used.
	/// This can be achieved by using the PreviousIndex within the UADigitalCameraComponent::OnRenderTargetIndexUpdated method.
	/** Render texture to apply to the on-screen camera representation of the last photo taken. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category="ADigitalCameraComponent|Params")
	TObjectPtr<UTextureRenderTarget2D> LastPhotoRenderTarget = nullptr;

	// INTERNAL
private:
	int32 RenderTargetIndex = 0;
	
};
